### ISSUE TITLE
non overlapping reads

### ISSUE THREAD

**Issue by aarandad** [aarandad/ampseq_workflow#20]
The only problem we should try to solve is in the cases where  we have non overlapping reads where the difference is in how many bases are good before the N’s; and the case where one of them overlaps and the other one doesn’t. 
I would not collapse reads that are not an exact match 

Case 1: 
you have 2 asvs:
AGCATCGACTACTAGCT NNNNNNNNNN GATCAGCTAGCATCGACTA
AGCATCGACTACTAGC NNNNNNNNNN GATCAGCTAGCATCGACTA
Those 2 should be the same ASV, it’s just that one of them had that T that was of good quality and made it thru and the other one didn’t. 

Problem would be if you have this:
AGCATCGACTACTAGCT NNNNNNNNNN GATCAGCTAGCATCGACTA
AGCATCGACTACTAGC NNNNNNNNNN GATCAGCTAGCATCGACTA
AGCATCGACTACTAGCA NNNNNNNNNN GATCAGCTAGCATCGACTA
Where it’s unclear where the short one should go. One option would be to truncate all R1 to the C.
I actually think that it’d be more conservative to just truncate and collapse all to 
AGCATCGACTACTAGC NNNNNNNNNN GATCAGCTAGCATCGACTA
Since otherwise we’re reporting an allele that doesn’t have info on that one base. 

Case 2:
AGCATCGACTACTAGCT NNNNNNNNNN GATCAGCTAGCATCGACTA
AGCATCGACTACTAGCTGATCGCGATCAGCTAGCATCGACTA
For whatever reason some of the reads didn’t get through. 
I don’t think this is going to be common. And I think it makes sense to be conservative and make all non overlapping as above. 
In fact, the way that it’s written now, you shouldn’t get overlapping and non overlapping reads for the same locus…

**Comment by aarandad** [comment]
if we wanna be fancy we could map the on overlapping ones to the reference and add as many N's to make it have the same length of the reference

**Comment by palmbri** [comment]
merged
