### ISSUE TITLE
change file names to make them more intuitive

### ISSUE THREAD

**Issue by aarandad** [aarandad/ampseq_workflow#24]
ALL_filt.AMPLICONsummary.txt 
 and ALL_filt.final.AMPLICONsummary.txt
what is the difference? 
**Call amplicon_coverage.txt**

ALL_trim.AMPLICONsummary.txt, no need to keep? it's only intermedite step for quality report?

ALL_SAMPLEsummary.txt -> **sample_coverage.txt**

dada2_overlaps.RData -> **dada2_output.RData**

**Comment by palmbri** [comment]
![image](https://user-images.githubusercontent.com/103962129/191859928-4d4ca3ff-29ed-431f-b653-31ca6c39f06c.png)
