### ISSUE TITLE
pandoc version

### ISSUE THREAD

**Issue by aarandad** [aarandad/ampseq_workflow#9]
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
  Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
  Execution halted

**Comment by palmbri** [comment]
@aarandad - what environment was this in? on wynton I have 1.12.3.1 
I'm guessing that part is breaking the workflow. Per https://github.com/benjjneb/dada2/issues/1444, the above is a known issue and can be ignored.

**Comment by palmbri** [comment]
This could be resolved with a docker container

**Comment by aarandad** [comment]
sorry, just read those questions. 
Ubuntu.
I just pulled the latest release and ran it and I'm getting the same issue

 Warning message:
  `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
  Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
  Execution halted

**Comment by aarandad** [comment]
works after downloading and installing from 
https://github.com/jgm/pandoc/releases/tag/2.19.2

**Comment by aarandad** [comment]
what's that used for?
can we go around it?

**Comment by palmbri** [comment]
it's needed to by rmarkdown to convert from markdown -> html. I don't think there is a way around it

**Comment by palmbri** [comment]
```
We assume you have already installed R (https://www.r-project.org/) ([R Core Team 2022](https://bookdown.org/yihui/rmarkdown/installation.html#ref-R-base)) and the RStudio IDE (https://www.rstudio.com/). RStudio is not required but recommended, because it makes it easier for an average user to work with R Markdown. If you do not have RStudio IDE installed, you will have to install Pandoc (http://pandoc.org/), otherwise there is no need to install Pandoc separately because RStudio has bundled it. 
```
From: https://bookdown.org/yihui/rmarkdown/installation.html
Unless they have RStudio, will need to be installed separately
